# Generated by Django 5.0.3 on 2024-03-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': ('News category',), 'verbose_name_plural': 'News categories'},
        ),
    ]
