# Generated by Django 5.0.3 on 2024-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsInfo', '0002_alter_categorymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_image',
            field=models.FileField(upload_to='news_images'),
        ),
    ]
