# Generated by Django 5.0.3 on 2024-03-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsInfo', '0004_alter_newsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsInfo.categorymodel'),
        ),
    ]
